# **1. PyTorch**

PyTorch는 파이썬 기반의 오픈소스 **딥러닝 프레임워크로, 파이썬 코드로 AI 모델을 직관적으로 만들고 학습할 수 있도록 도와주는 도구**이다. 특히 동적 계산 그래프 방식을 사용하기 때문에 코드 실행 시점에 실시간으로 계산 흐름이 결정되어 디버깅과 수정이 쉽고, GPU 가속과 자동 미분 기능을 통해 대규모 모델도 빠르게 학습할 수 있다.

```
pip install torch
```

In [1]:
import torch

### ※ 동적 계산 그래프 방식
딥러닝 모델이 학습 및 예측을 수행할 때 **계산 그래프를 실행 시점(runtime)에 실시간으로 생성 및 수정하는 방식**이다. 이 방식은 조건문, 반복문 등 복잡한 논리 구조를 유연하게 처리할 수 있으며, 주로 PyTorch와 같은 프레임워크에서 사용된다. **계산 그래프는 입력 데이터를 바탕으로 연산을 수행하면서 그래프를 생성하고, 역전파를 통해 미분을 계산하며, 최종적으로 가중치를 업데이트하는 과정을 거친다.** 이러한 특성 덕분에 디버깅이 용이하고 연구 및 개발 속도가 빠르며 직관적인 코드 작성이 가능하다.

### **1. 스칼라**
스칼라(Scalar)는 **단 하나의 숫자(정수, 실수 등)만을 담는 자료형**을 말한다. 파이토치(PyTorch)에서 스칼라는 0차원 텐서(0-dimensional Tensor)로 표현한다. 즉, 텐서의 차원(Shape)이 전혀 없는 상태를 의미한다.

In [2]:
var1 = torch.tensor(5)

print(var1)
print(var1.shape) # torch.Size([]) -> 0차원 텐서

tensor(5)
torch.Size([])


In [3]:
var2 = torch.tensor([10])

print(var2)
print(var2.shape) # torch.Size([1]) -> 1차원 텐서. 스칼라가 아님

tensor([10])
torch.Size([1])


In [4]:
var2 = torch.tensor([10, 11, 12])

print(var2)
print(var2.shape) # torch.Size([3]) -> 텐서 개수, 차원 X

tensor([10, 11, 12])
torch.Size([3])


In [5]:
var3 = torch.tensor(3)
result = var1 + var3

print(result)
print(result.item()) # 숫자만 뽑을 때

tensor(8)
8


### **2. 벡터(Vector)**
벡터(Vector)는 **하나 이상의 원소가 일렬로 나열된 1차원 텐서(1D Tensor)를 의미**한다. 파이토치(PyTorch)에서 벡터는 일반적으로 torch.tensor([...]) 형태로 만들며, 이때 텐서의 shape(차원)가 (n,) 형태이다. 즉, 원소가 n개 들어 있으면 1차원 벡터가 된다.

In [6]:
var1 = torch.tensor([1.0, 2.0, 3.0])

print(var1)
print(var1.shape) # torch.Size([3]) -> 1차원 텐서

tensor([1., 2., 3.])
torch.Size([3])


In [7]:
var2 = var1 + 10
print(var2)

var3 = var1 * 2
print(var3)

tensor([11., 12., 13.])
tensor([2., 4., 6.])


In [8]:
var4 = torch.tensor([4.0, 5.0, 6.0])
result = var1 + var4

print(result)

tensor([5., 7., 9.])


### **3. 행렬**
행렬(Matrix)은 2차원 형태의 텐서로, 파이토치(PyTorch)에서는 **shape가 (m, n)처럼 2개의 차원을 가진 텐서**를 의미한다. 예를 들어, torch.tensor([[1, 2], [3, 4]])는 2행×2열 형태의 행렬이다. 행렬 연산에서는 행렬 곱셈, 원소별 연산, 전치(Transpose) 등이 자주 활용되며, 파이토치는 torch.mm 또는 @ 연산자를 통해 행렬 곱셈을 수행할 수 있다.

In [9]:
var1 = torch.tensor([[1, 2],
                  [3, 4]])
var2 = torch.tensor([[5, 6],
                  [7, 8]])

print(var1)
print(var1.shape) # torch.Size([2, 2]) -> 2차원 텐서

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [10]:
result1 = var1 + var2
print(result1)

result2 = var1 * var2
print(result2)
# 원소의 포지션별 연산

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])


In [11]:
result3 = torch.mm(var1, var2)
print(result3)

result4 = var1 @ var2
print(result4)

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


### **4. 다차원 텐서**
파이토치(PyTorch)에서 다차원 텐서란, **여러 축(차원)을 가지는 텐서**를 의미한다. 예를 들어, 0차원 텐서는 “스칼라(Scalar)”, 1차원 텐서는 “벡터(Vector)”, 2차원 텐서는 “행렬(Matrix)”, 그 이상의 3차원, 4차원 텐서 등을 통틀어 “다차원 텐서(Multi-dimensional Tensor)”라고 부른다. 다차원 텐서는 이미지, 음성, 동영상, 시계열 데이터를 비롯하여 여러 축을 필요로 하는 다양한 형태의 데이터를 표현할 때 쓴다.

In [12]:
var1 = torch.tensor([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]],

    [[9, 10],
     [11, 12]]
])

print(var1)
print(var1.shape)  # torch.Size([2, 2, 2])

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
torch.Size([3, 2, 2])


![텐서](./images/텐서.png)

# **2. 텐서**

PyTorch의 텐서(Tensor)는 딥러닝 모델에서 데이터를 다룰 때 사용되는 기본 데이터 구조입니다. 텐서는 다차원 배열로, NumPy의 배열과 비슷하지만, GPU에서 연산을 수행할 수 있다는 점에서 차이가 있다. PyTorch의 텐서는 데이터의 표현뿐만 아니라, 자동 미분(autograd) 기능을 제공하여 딥러닝 모델의 학습을 도와준다.

In [13]:
data = [
  [1, 2],
  [3, 4]
]
t1 = torch.tensor(data)

print(t1)

tensor([[1, 2],
        [3, 4]])


In [14]:
t1 = torch.tensor([5])
t2 = torch.tensor([7])
ndarr1 = (t1 + t2).numpy() # numpy ndarray 형태로 변환

print(ndarr1)
print(type(ndarr1))

[12]
<class 'numpy.ndarray'>


In [15]:
result = ndarr1 * 10
t3 = torch.from_numpy(result) # numpy ndarray를 텐서로 형태 변환

print(t3)
print(type(t3))

tensor([120])
<class 'torch.Tensor'>


In [16]:
t1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(t1[0])
print(t1[:, 0])
print(t1[:, -1])
print(t1[..., -1])

tensor([1, 2, 3, 4])
tensor([1, 5, 9])
tensor([ 4,  8, 12])
tensor([ 4,  8, 12])


In [17]:
t1 = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])

print(t1.shape)
print(t1[..., -1]) # 첫 번째와 두 번째 차원을 유지. 마지막 차원만 선택

torch.Size([2, 2, 3])
tensor([[ 3,  6],
        [ 9, 12]])


# **3. GPU 사용**

GPU(Graphics Processing Unit)는 그래픽 처리 장치로, 주로 이미지 렌더링과 같은 대규모 병렬 계산을 수행하는 데 최적화된 하드웨어이다. 원래는 그래픽 처리를 위해 설계되었지만, 최근에는 인공지능(AI) 및 딥러닝의 연산 가속기로 널리 사용되고 있다. 딥러닝은 수천, 수만 개의 행렬 및 벡터 연산을 필요로 하다(여러 개의 쉬운 연산). GPU는 여러 개의 코어를 사용하여 이 연산을 병렬로 처리할 수 있다. 따라서, GPU는 딥러닝 에 최적화된 구조를 가지고 있다.

### ※ 무료와 Pro의 차이

![GPU](./images/GPU.png)

In [18]:
# 실행 장치 선택
if torch.cuda.is_available(): # NVIDIA 계열 GPU 사용 여부
    device = torch.device("cuda")
    device_name = torch.cuda.get_device_name(0) # Apple MAC GPU

elif torch.backends.mps.is_available():
    device = torch.device("mps")
    device_name = "Apple Silicon GPU (MPS)"

else:
    device = torch.device("cpu")
    device_name = "CPU"

print(f"사용 장치 : {device}")
print(f"장치 정보 : {device_name}")

사용 장치 : cpu
장치 정보 : CPU


In [19]:
data = [
  [1, 2],
  [3, 4]
]

t1 = torch.tensor(data) # GPU를 연결해 놓았더라도 CPU 사
print(t1.is_cuda)

t1 = t1.cuda() # GPU로 옮기기
print(t1.is_cuda)

t1 = t1.cpu() # CPU로 옮기기
print(t1.is_cuda)

False


AssertionError: Torch not compiled with CUDA enabled

In [ ]:
t1 = torch.tensor([
    [1, 1],
    [2, 2]
]).cuda()

t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

# print(torch.matmul(t1, t2)) >> 오류 발생(t1: GPU, t2: CPU)
print(torch.matmul(t1.cpu(), t2))
print(f"Device: {t1.device}") # t1 자체가 CPU 연산으로 바뀌진 않음

# **4. 텐서의 연산과 함수**

In [ ]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])
t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)

In [ ]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])
t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

print(t1.matmul(t2))
print(torch.matmul(t1, t2))

In [ ]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(t1)
print(t1.mean()) # 전체 원소에 대한 평균
print(t1.mean(dim=0)) # 각 열에 대하여 평균 계산
print(t1.mean(dim=1)) # 각 행에 대하여 평균 계산

In [ ]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(t1)
print(t1.sum()) # 전체 원소에 대한 합계
print(t1.sum(dim=0)) # 각 열에 대하여 합계 계산
print(t1.sum(dim=1)) # 각 행에 대하여 합계 계산

In [ ]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(t1)
print(t1.argmax()) # 전체 원소에 대한 최댓값의 인덱스
print(t1.argmax(dim=0)) # 각 열에 대하여 최댓값의 인덱스 계산
print(t1.argmax(dim=1)) # 각 행에 대하여 최댓값의 인덱스 계산

In [ ]:
t1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# dim: 텐서를 이어 붙이기 위한 축
# 0번 축(행)을 기준으로 이어 붙이기
result = torch.cat([t1, t1, t1], dim=0)
print(result)

# 1번 축(열)을 기준으로 이어 붙이기
result = torch.cat([t1, t1, t1], dim=1)
print(result)

In [ ]:
t1 = torch.tensor([2], dtype=torch.int)
t2 = torch.tensor([5.0])

print(t1.dtype)
print(t2.dtype)

# 텐서 t1는 자동으로 float32형으로 형변환 처리
print(t1 + t2)
# 텐서 t2를 int32형으로 형변환하여 덧셈 수행
print(t1 + t2.type(torch.int32))

In [ ]:
# view()는 텐서의 모양을 변경할 때 사용한다.
# 이때, 텐서(tensor)의 순서는 변경되지 않는다.
t1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
t2 = t1.view(4, 2)
print(t2)

# t1의 값을 변경하면 t2도 변경(가상의 view이기 때문)
t1[0] = 7
print(t1)
print(t2)

# t1의 값을 복사(copy)한 뒤에 변경
t3 = t1.clone().view(4, 2)
t1[0] = 9 # t1의 clone을 view했기 때문에 안 바뀜
print(t3)

In [ ]:
t1 = torch.rand((64, 5, 3))
print(t1.shape)

t2 = t1.permute(2, 1, 0) # 차원 자체를 교환
print(t2.shape) # (3, 5, 64)의 형태

In [ ]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(t1.shape)

# 첫 번째 축에 차원 추가
t1 = t1.unsqueeze(0)
print(t1)
print(t1.shape)

# 네 번째 축에 차원 추가
t1 = t1.unsqueeze(3)
print(t1)
print(t1.shape)

In [ ]:
# 크기가 1인 차원 제거, squeeze(dim): 특정 차원이 1인 경우에만 차원을 제거
t1 = t1.squeeze()
print(t1)
print(t1.shape)

# **5. 자동 미분과 기울기**

### **1. 미분**
미분(Differentiation)​이란 어떤 값이 얼마나 빠르게 변하는지를 계산하는 수학적인 방법이다. 쉽게 말해, 입력값(x)이 아주 조금 변했을 때 출력값(y)이 얼마나 변하는지​를 나타내는 기울기(변화율)​를 구하는 것이다. 딥러닝에서는 이 기울기를 이용해 모델의 가중치가 결과에 얼마나 영향을 주는지 계산하고, 이를 바탕으로 가중치를 조금씩 수정하여 모델의 성능을 향상시킨다.

```
자동미분을 이해하기 위해 가장 간단한 함수인 y = x²를 살펴보겠습니다.

예를 들어 x = 3이라면,
y = 3² = 9

이 함수를 미분하면 아래와 같습니다.
y를 x에 대해 미분하면 2x
dy/dx = 2x

여기에 x = 3을 대입하면,
dy/dx = 2 × 3 = 6

x가 아주 조금 변할 때 y가 얼마나 변하는지를 나타내는 비율(기울기)
즉, x = 3인 지점에서 함수의 기울기(미분값)는 6이라는 의미입니다.
```

In [ ]:
# 미분할 변수 x 생성
# 이 값이 이후 계산 결과에 얼마나 영향을 주는지 미분할 예정
x = torch.tensor(3.0, requires_grad=True)

# 함수 y = x²
y = x ** 2

# y를 기준으로 x에 대한 미분값 계산
# y에서 출발하여 계산 그래프를 거꾸로 이동하면서 미분합니다.
# 정방향 계산: x = 3 > y = x² > y = 9
# 역방향 계산: y > dy/dx = 2x > x = 3이므로 6
y.backward() # PyTorch 메소드

print("x 값:", x)
print("y 값:", y)
# 현재 x=3 근처에서 x가 조금 변할 때 y가 얼마나 민감하게 변하는지를 나타냅니다.
print("x의 미분값:", x.grad)